- name: Install unbound
  become: true
  apt: 
    name:
      - ca-certificates
      - unbound
      - unbound-host
    state: present
    update_cache: true

- name: Download the list of root DNS servers
  become: true
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/root.hints
    owner: unbound
    group: unbound

- name: Generate unbound config
  become: true
  template:
    src: "templates/unbound.conf"
    dest: "/etc/unbound/unbound.conf"
  notify: "reboot the server"

- name: Enable and start unbound service
  become: true
  systemd:
    name: unbound
    enabled: yes
    state: started
  notify: "reboot the server"

- name: Set var/lib/unbound ownership
  become: true
  file:
    path: /var/lib/unbound
    owner: unbound
    group: unbound
    recurse: yes 

- name: Turn off resolved (in Ubuntu 18.04)
  become: true
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: 'DNSStubListener=no'
    create: no
  notify: "reboot the server"
  register: remove_resolved

- name: Disable the resolved service (in Ubuntu 18.04)  # https://askubuntu.com/a/907249
  become: true
  systemd:
    name: systemd-resolved.service
    enabled: no
    state: stopped
  notify: "reboot the server"
  when: remove_resolved.changed  # Lest we make errors for those without resolved
  
- name: Delete the resolved-symlinked resolv.conf (in Ubuntu 18.04)  # https://askubuntu.com/a/907249
  become: true
  file:
    path: "/etc/resolv.conf"
    state: absent
  notify: "reboot the server"
  when: remove_resolved.changed

# TODO: This needs further testing (run the whole playbook against a freshly
# re-imaged server)
#
# https://www.pcextreme.nl/community/d/94-unbound-local-dns-cache-on-ubuntu-and-centos
- name: Configure the system to use the local unbound DNS (in Ubuntu 18.04)
  become: true
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 127.0.0.1'
    create: yes
  when: remove_resolved.changed
