- name: Enable IPv4 traffic forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable IPv4 forwarding continued
  command: echo 1 > /proc/sys/net/ipv4/ip_forward

#Set up firewall rules
- name: Track input chain
  become: true
  iptables:
    chain: INPUT
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Track forward chain  
  become: true
  iptables:
    chain: FORWARD
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow incoming wireguard connections    
  become: true
  iptables:
    chain: INPUT
    protocol: udp
    match: udp
    destination_port: "{{ vpn_port }}"
    ctstate: NEW
    jump: ACCEPT
   
- name: Allow recursive DNS tcp    
  become: true
  iptables:
    chain: INPUT
    source: "{{ vpn_network }}.0/24"
    protocol: tcp
    match: tcp
    destination_port: 53
    ctstate: NEW
    jump: ACCEPT
  
- name: Allow recursive DNS udp  
  become: true
  iptables:
    chain: INPUT
    source: "{{ vpn_network }}.0/24"
    protocol: udp
    match: udp
    destination_port: 53
    ctstate: NEW
    jump: ACCEPT
    
- name: Allow forwarding of packets that stay in the tunnel 
  become: true
  iptables:
    chain: FORWARD
    in_interface: wg0
    match: conntrack
    out_interface: wg0
    ctstate: NEW
    jump: ACCEPT

- name: Set up NAT
  become: true
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ vpn_network }}.0/24"
    out_interface: "{{ ansible_default_ipv4.interface }}"
    jump: MASQUERADE  

- name: Install iptables-persistent
  become: true
  apt: pkg=iptables-persistent state=present update_cache=true

- name: Set up iptables persistence
  become: true
  command: netfilter-persistent save


